sudo: required
language: c
services:
- docker
before_install:
- docker pull tg9541/docker-sdcc:V3.8.6
install:
- docker run -v `pwd`:/home tg9541/docker-sdcc:V3.8.6 /bin/sh -c "sdcc --version ;
  sstm8 -version"
script: docker run -v `pwd`:/home tg9541/docker-sdcc:V3.8.6 /bin/sh -c "cd /home &&
  make release"
deploy:
  provider: releases
  api_key:
    secure: o/mjgP/dMwKE2Z3oZ+Z0kgPRv522musZv4i4YRw/RZZ1jIKvKBGOU6YAnm2qUEW2eJzkq+V8taF2ifOvrLldRweowy6p/WRTLT52+EXIHUCtFaO3YfOaxAK/qGlHoeHoUiTM2AifVjLDg7Jzs2UYchBM3v/qjTU02ylnVKmgHCIkqr4h+VkfyZXI7bTbwm2dThv+eYcuZrv87HX3mCq5I7iBN1d7NzBcp3Sy3fk2m1UkzONR4lKs0m2FfNONtZQ/bGmbYOFyruR4U83ISByICbv5fXqU5MzQ02ffepEfKtWFmuNLUVVMZdY5eb/vSyg94FgMfMbURQJmU9qLZU2pfFedRe72mByAmWyATQu/HXXyYGjxl927+ivUzD/b4RNeexE73kov36rhP79kLYisWVy50gsL9LuxBkBzeQVOfMBqJ4hoCQwUlzqF7jpVPcCucjXwlpaPZpE3lRKIC/T26wv6lNXUanwqEKb1ck0q28v94tFbv7LcRpC8Ce1ATLMxWEhhImkduSQXEGwicDbg2kwgzcKy2KKOb1sozb7S12K1lft2HDYSYcu8LYcdB75+MEdYXtgAq5q5rauL/kpGHyZ+m25YXIFc9H98pLMe2o5IuLj/X6A9LbsLL2dhLdxSjbFJFTIqSHVW4NN+N/Ouz43B4RK+1WnXbnC3TAneUws=
  file: dmo
  on:
    repo: TG9541/W1209
